# Generated by Django 4.2.24 on 2025-10-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chesscom_id', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('white_player', models.CharField(max_length=50)),
                ('black_player', models.CharField(max_length=50)),
                ('kris_rating', models.IntegerField()),
                ('opp_rating', models.IntegerField()),
                ('kris_result', models.CharField(max_length=10)),
                ('opp_result', models.CharField(max_length=10)),
                ('time_control', models.CharField(max_length=20)),
                ('pgn', models.TextField()),
                ('opening', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
